# Generated by Django 6.0 on 2025-12-22 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fleet", "0002_flight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de la séance"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Thème de la séance"),
                ),
                ("comments", models.TextField(verbose_name="Commentaire Instructeur")),
                (
                    "next_steps",
                    models.TextField(
                        blank=True, verbose_name="À travailler prochainement"
                    ),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "À revoir (1/5)"),
                            (2, "En cours (2/5)"),
                            (3, "Acquis (3/5)"),
                            (4, "Maîtrisé (4/5)"),
                            (5, "Excellent (5/5)"),
                        ],
                        default=3,
                        verbose_name="Note globale",
                    ),
                ),
                (
                    "flight",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_report",
                        to="fleet.flight",
                        verbose_name="Vol associé",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Instructeur",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leçon / Séance",
                "verbose_name_plural": "Livret de Progression",
                "ordering": ["-date"],
            },
        ),
    ]
