# Generated by Django 5.2.7 on 2025-12-23 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0004_alter_aircraft_options_alter_flight_options_and_more"),
        ("instruction", "0002_alter_lesson_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Code exercice")),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de l'exercice"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description detaillee"),
                ),
                (
                    "objectives",
                    models.TextField(blank=True, verbose_name="Objectifs pedagogiques"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Obligatoire"),
                ),
                (
                    "is_solo_exercise",
                    models.BooleanField(default=False, verbose_name="Exercice solo"),
                ),
            ],
            options={
                "verbose_name": "Exercice de formation",
                "verbose_name_plural": "Exercices de formation",
                "ordering": ["phase__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la phase"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "target_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Nombre d'heures recommande pour cette phase",
                        max_digits=5,
                        verbose_name="Heures cibles",
                    ),
                ),
                (
                    "is_solo_allowed",
                    models.BooleanField(default=False, verbose_name="Solo autorise"),
                ),
            ],
            options={
                "verbose_name": "Phase de formation",
                "verbose_name_plural": "Phases de formation",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["-date"],
                "verbose_name": "Lecon / Seance",
                "verbose_name_plural": "Livret de progression",
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="areas_to_improve",
            field=models.TextField(blank=True, verbose_name="Points a ameliorer"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="briefing_content",
            field=models.TextField(blank=True, verbose_name="Contenu briefing"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="instructor_signature",
            field=models.BooleanField(
                default=True, verbose_name="Signe par instructeur"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("INSTRUCTION", "Vol instruction DC"),
                    ("SOLO_SUP", "Solo supervise"),
                    ("SOLO", "Solo"),
                    ("CHECK", "Vol de controle"),
                    ("BRIEFING", "Briefing sol"),
                    ("EXAM", "Examen"),
                ],
                default="INSTRUCTION",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="objectives",
            field=models.TextField(blank=True, verbose_name="Objectifs de la seance"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="solo_authorization_notes",
            field=models.TextField(blank=True, verbose_name="Notes autorisation solo"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="solo_authorized",
            field=models.BooleanField(default=False, verbose_name="Solo autorise"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="strong_points",
            field=models.TextField(blank=True, verbose_name="Points forts"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="student_signature",
            field=models.BooleanField(default=False, verbose_name="Vu par eleve"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAVOK", "CAVOK"),
                    ("VFR", "VFR"),
                    ("MVFR", "VFR marginal"),
                    ("IFR", "IFR"),
                ],
                max_length=10,
                verbose_name="Conditions meteo",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="wind",
            field=models.CharField(
                blank=True, help_text="Ex: 180/15kt", max_length=50, verbose_name="Vent"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="comments",
            field=models.TextField(verbose_name="Commentaire instructeur"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de la seance"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="flight",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_report",
                to="fleet.flight",
                verbose_name="Vol associe",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="grade",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "A revoir (1/5)"),
                    (2, "En cours (2/5)"),
                    (3, "Acquis (3/5)"),
                    (4, "Maitrise (4/5)"),
                    (5, "Excellent (5/5)"),
                ],
                default=3,
                verbose_name="Note globale",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="next_steps",
            field=models.TextField(
                blank=True, verbose_name="A travailler prochainement"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eleve",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Theme de la seance"),
        ),
        migrations.CreateModel(
            name="StudentProgression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date inscription formation",
                    ),
                ),
                (
                    "target_license",
                    models.CharField(
                        choices=[
                            ("LAPL", "LAPL(A)"),
                            ("PPL", "PPL(A)"),
                            ("CPL", "CPL(A)"),
                            ("BB", "Brevet de Base"),
                        ],
                        default="PPL",
                        max_length=20,
                        verbose_name="Objectif licence",
                    ),
                ),
                (
                    "first_solo_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date premier solo"
                    ),
                ),
                (
                    "first_solo_nav_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date premier solo nav"
                    ),
                ),
                (
                    "theory_exam_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date examen theorique"
                    ),
                ),
                (
                    "theory_exam_passed",
                    models.BooleanField(default=False, verbose_name="Theorique reussi"),
                ),
                (
                    "practical_exam_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date examen pratique"
                    ),
                ),
                (
                    "practical_exam_passed",
                    models.BooleanField(default=False, verbose_name="Pratique reussi"),
                ),
                (
                    "license_obtained_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date obtention licence"
                    ),
                ),
                (
                    "total_instruction_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Heures en double commande",
                        max_digits=6,
                        verbose_name="Heures DC",
                    ),
                ),
                (
                    "total_solo_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=6,
                        verbose_name="Heures solo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Formation active"),
                ),
                (
                    "primary_instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_students",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Instructeur principal",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_progression",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eleve",
                    ),
                ),
                (
                    "current_phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_students",
                        to="instruction.trainingphase",
                        verbose_name="Phase actuelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression eleve",
                "verbose_name_plural": "Progressions eleves",
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="exercises_practiced",
            field=models.ManyToManyField(
                blank=True,
                related_name="lessons",
                to="instruction.trainingexercise",
                verbose_name="Exercices travailles",
            ),
        ),
        migrations.AddField(
            model_name="trainingexercise",
            name="phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="instruction.trainingphase",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="instruction.trainingphase",
                verbose_name="Phase",
            ),
        ),
        migrations.CreateModel(
            name="LessonExerciseEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_before",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("-", "Non vu"),
                            ("P", "Presente"),
                            ("E", "En cours d'acquisition"),
                            ("A", "Acquis"),
                            ("+", "Maitrise / Expert"),
                        ],
                        max_length=1,
                        verbose_name="Niveau avant",
                    ),
                ),
                (
                    "level_after",
                    models.CharField(
                        choices=[
                            ("-", "Non vu"),
                            ("P", "Presente"),
                            ("E", "En cours d'acquisition"),
                            ("A", "Acquis"),
                            ("+", "Maitrise / Expert"),
                        ],
                        max_length=1,
                        verbose_name="Niveau apres",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Commentaires")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_evaluations",
                        to="instruction.lesson",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instruction.trainingexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation exercice",
                "verbose_name_plural": "Evaluations exercices",
                "unique_together": {("lesson", "exercise")},
            },
        ),
        migrations.CreateModel(
            name="ExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("-", "Non vu"),
                            ("P", "Presente"),
                            ("E", "En cours d'acquisition"),
                            ("A", "Acquis"),
                            ("+", "Maitrise / Expert"),
                        ],
                        default="-",
                        max_length=1,
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "last_practiced",
                    models.DateField(
                        blank=True, null=True, verbose_name="Derniere pratique"
                    ),
                ),
                (
                    "instructor_notes",
                    models.TextField(blank=True, verbose_name="Notes instructeur"),
                ),
                (
                    "student_progression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_progress",
                        to="instruction.studentprogression",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="instruction.trainingexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression exercice",
                "verbose_name_plural": "Progressions exercices",
                "unique_together": {("student_progression", "exercise")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="trainingexercise",
            unique_together={("phase", "code")},
        ),
    ]
