# Generated by Django 6.0 on 2025-12-22 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant (€)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Crédit (Versement)"),
                            ("DEBIT", "Débit (Vol/Achat)"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Libellé"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture Comptable",
                "verbose_name_plural": "Écritures Comptables",
                "ordering": ["-date"],
            },
        ),
    ]
