# Generated by Django 5.2.7 on 2025-12-23 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0002_alter_reservation_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-start_time"],
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="destination",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Destination"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="eligibility_checked",
            field=models.BooleanField(
                default=False, verbose_name="Eligibilite verifiee"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="eligibility_warnings",
            field=models.TextField(
                blank=True, verbose_name="Avertissements eligibilite"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="force_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si un responsable autorise malgre les restrictions",
                verbose_name="Autorise malgre avertissements",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="force_allowed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorized_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Autorise par",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="passengers_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Nombre de passagers"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("CONFIRMED", "Confirmee"),
                    ("CANCELLED", "Annulee"),
                    ("COMPLETED", "Terminee"),
                ],
                default="CONFIRMED",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.DateTimeField(verbose_name="Debut"),
        ),
    ]
