# Generated by Django 6.0 on 2025-12-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Immatriculation"
                    ),
                ),
                ("model_name", models.CharField(max_length=50, verbose_name="Modèle")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="aircrafts/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Coût à l'heure de vol",
                        max_digits=6,
                        verbose_name="Tarif Horaire (€)",
                    ),
                ),
                (
                    "current_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Heures Totales (Cellule)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponible"),
                            ("MAINTENANCE", "En Maintenance"),
                            ("GROUNDED", "Cloué au sol (Panne)"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avion",
                "verbose_name_plural": "Avions",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Type d'échéance"),
                ),
                (
                    "due_at_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Butée Horaire",
                    ),
                ),
                (
                    "due_at_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Butée Calendaire"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to="fleet.aircraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Échéance Maintenance",
                "verbose_name_plural": "Échéances Maintenance",
            },
        ),
    ]
