# Generated by Django 6.0 on 2025-12-22 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "hour_meter_start",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Compteur Départ"
                    ),
                ),
                (
                    "hour_meter_end",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Compteur Arrivée"
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=5,
                        verbose_name="Durée (h)",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=8,
                        verbose_name="Coût (€)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="fleet.aircraft",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vol Réalisé",
                "verbose_name_plural": "Vols Réalisés",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
