# Generated by Django 5.2.7 on 2025-12-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0002_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="block_off",
            field=models.TimeField(blank=True, null=True, verbose_name="Bloc Départ"),
        ),
        migrations.AddField(
            model_name="flight",
            name="block_on",
            field=models.TimeField(blank=True, null=True, verbose_name="Bloc Arrivée"),
        ),
        migrations.AddField(
            model_name="flight",
            name="complaints",
            field=models.TextField(
                blank=True, verbose_name="Observations Techniques (Squawks)"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="fuel_added",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                verbose_name="Essence Ajoutée (L)",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="landing_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Atterrissage"),
        ),
        migrations.AddField(
            model_name="flight",
            name="landings_count",
            field=models.IntegerField(default=1, verbose_name="Nb Atterrissages"),
        ),
        migrations.AddField(
            model_name="flight",
            name="oil_added",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=4,
                verbose_name="Huile Ajoutée (L)",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="takeoff_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Décollage"),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancedeadline",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
