# Generated by Django 5.2.7 on 2025-12-23 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet", "0003_flight_block_off_flight_block_on_flight_complaints_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aircraft",
            options={
                "ordering": ["registration"],
                "verbose_name": "Aeronef",
                "verbose_name_plural": "Aeronefs",
            },
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Vol Realise",
                "verbose_name_plural": "Vols Realises",
            },
        ),
        migrations.AlterModelOptions(
            name="maintenancedeadline",
            options={
                "ordering": ["due_at_date", "due_at_hours"],
                "verbose_name": "Echeance Maintenance",
                "verbose_name_plural": "Echeances Maintenance",
            },
        ),
        migrations.AddField(
            model_name="aircraft",
            name="category",
            field=models.CharField(
                choices=[
                    ("SEP", "Monomoteur Piston"),
                    ("MEP", "Multimoteur Piston"),
                    ("SET", "Monomoteur Turboprop"),
                    ("MET", "Multimoteur Turboprop"),
                    ("ULM", "ULM"),
                ],
                default="SEP",
                max_length=10,
                verbose_name="Categorie",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="cdn_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date expiration CDN"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="cdn_issue_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date emission CDN"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="cdn_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numero CDN"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="cdn_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="fleet/documents/",
                verbose_name="Scan CDN",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="cruise_speed",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Vitesse croisiere (kt)"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="cycles_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Nombre de vols", verbose_name="Cycles cellule"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="empty_weight",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Masse a vide (kg)"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="engine_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Heures moteur",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="engine_model",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Modele moteur"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="engine_overhaul_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date derniere revision moteur"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="engine_serial",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N. serie moteur"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="engine_tbo",
            field=models.PositiveIntegerField(
                default=2000,
                help_text="Time Before Overhaul",
                verbose_name="TBO moteur (h)",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="engine_tsoh",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Heures depuis revision (TSOH)",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="equipment_notes",
            field=models.TextField(blank=True, verbose_name="Notes equipements"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="flight_manual_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="fleet/manuals/",
                verbose_name="Manuel de vol (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="fuel_capacity",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=6,
                verbose_name="Capacite carburant (L)",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="fuel_consumption",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=5,
                verbose_name="Consommation horaire (L/h)",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("100LL", "100LL (Avgas)"),
                    ("UL91", "UL91 (Sans plomb)"),
                    ("JETA1", "JET-A1 (Kerosene)"),
                    ("MOGAS", "Mogas (Auto)"),
                ],
                default="100LL",
                max_length=10,
                verbose_name="Type carburant",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="gps_model",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Modele GPS"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="has_adf",
            field=models.BooleanField(default=False, verbose_name="ADF"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="has_adsb",
            field=models.BooleanField(default=False, verbose_name="ADS-B Out"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="has_autopilot",
            field=models.BooleanField(default=False, verbose_name="Pilote automatique"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="has_dme",
            field=models.BooleanField(default=False, verbose_name="DME"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="has_efis",
            field=models.BooleanField(default=False, verbose_name="EFIS/Glass cockpit"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="has_gps",
            field=models.BooleanField(default=False, verbose_name="GPS"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="has_ils",
            field=models.BooleanField(default=False, verbose_name="ILS"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="has_transponder",
            field=models.BooleanField(default=True, verbose_name="Transpondeur"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="has_vor",
            field=models.BooleanField(default=True, verbose_name="VOR"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="hourly_rate_instruction",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarif avec instructeur (hors frais FI)",
                max_digits=6,
                null=True,
                verbose_name="Tarif horaire instruction (Euros)",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="instruction_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                max_digits=5,
                verbose_name="Frais instruction/heure (Euros)",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="insurance_company",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Compagnie assurance"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="insurance_expiry",
            field=models.DateField(
                blank=True, null=True, verbose_name="Expiration assurance"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="insurance_policy_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numero police"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="insurance_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="fleet/documents/",
                verbose_name="Scan assurance",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="is_club_owned",
            field=models.BooleanField(default=True, verbose_name="Propriete du club"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Constructeur"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="max_range",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Distance franchissable (NM)"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="mtow",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Masse max decollage (kg)"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="num_seats",
            field=models.PositiveSmallIntegerField(
                default=4, verbose_name="Nombre de places"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="oil_capacity",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=4,
                verbose_name="Capacite huile (L)",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="owner_name",
            field=models.CharField(
                blank=True,
                help_text="Si non club",
                max_length=100,
                verbose_name="Proprietaire",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="propeller_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Heures helice",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="propeller_model",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Modele helice"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="propeller_serial",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N. serie helice"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="propeller_tbo",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="TBO helice (h)"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="radio_license_expiry",
            field=models.DateField(
                blank=True, null=True, verbose_name="Expiration licence radio"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="radio_license_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numero licence radio"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="registration_certificate_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date certificat immat."
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="registration_certificate_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="fleet/documents/",
                verbose_name="Scan certificat immat.",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numero de serie"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="transponder_mode",
            field=models.CharField(
                default="Mode S", max_length=20, verbose_name="Mode transpondeur"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="usable_fuel",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=6,
                verbose_name="Carburant utilisable (L)",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="year_of_manufacture",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Annee construction"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="arrival_airport",
            field=models.CharField(
                default="LFNE", max_length=10, verbose_name="Aerodrome arrivee"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="complaint_resolved",
            field=models.BooleanField(default=True, verbose_name="Squawk resolu"),
        ),
        migrations.AddField(
            model_name="flight",
            name="copilot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flights_as_copilot",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Second pilote/Instructeur",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_airport",
            field=models.CharField(
                default="LFNE", max_length=10, verbose_name="Aerodrome depart"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_type",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Local"),
                    ("NAV", "Navigation"),
                    ("INSTRUCTION", "Instruction"),
                    ("CHECK", "Controle"),
                    ("EXAM", "Examen"),
                    ("FERRY", "Convoyage"),
                    ("MAINTENANCE", "Vol maintenance"),
                ],
                default="LOCAL",
                max_length=20,
                verbose_name="Type de vol",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="fuel_on_arrival",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=6,
                null=True,
                verbose_name="Carburant arrivee (L)",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="fuel_on_departure",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=6,
                null=True,
                verbose_name="Carburant depart (L)",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="landings_day",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Atterrissages jour"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="landings_night",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Atterrissages nuit"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="passengers_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Passagers"),
        ),
        migrations.AddField(
            model_name="flight",
            name="pilot_signature",
            field=models.BooleanField(default=True, verbose_name="Signe par pilote"),
        ),
        migrations.AddField(
            model_name="flight",
            name="resolution_notes",
            field=models.TextField(blank=True, verbose_name="Notes resolution"),
        ),
        migrations.AddField(
            model_name="flight",
            name="route",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Route/Escales"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="signature_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date signature"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="completed_by",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Realise par (atelier)"
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="completion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date realisation"
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="completion_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Heures a la realisation",
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="completion_notes",
            field=models.TextField(blank=True, verbose_name="Notes realisation"),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="deadline_type",
            field=models.CharField(
                choices=[
                    ("50H", "Visite 50 heures"),
                    ("100H", "Visite 100 heures"),
                    ("ANNUAL", "Visite annuelle"),
                    ("CDN", "Renouvellement CDN"),
                    ("ENGINE", "Revision moteur"),
                    ("PROPELLER", "Revision helice"),
                    ("AD", "Consigne de navigabilite (AD)"),
                    ("SB", "Service Bulletin"),
                    ("OTHER", "Autre"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Type echeance",
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cout estime (Euros)",
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Effectuee"),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Basse"),
                    ("MEDIUM", "Moyenne"),
                    ("HIGH", "Haute"),
                    ("CRITICAL", "Critique"),
                ],
                default="MEDIUM",
                max_length=10,
                verbose_name="Priorite",
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Reference (AD/SB)"
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="tolerance_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Jours de tolerance apres butee",
                verbose_name="Tolerance jours",
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="tolerance_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Heures de tolerance apres butee",
                max_digits=5,
                verbose_name="Tolerance horaire",
            ),
        ),
        migrations.AddField(
            model_name="maintenancedeadline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="current_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Heures cellule",
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                verbose_name="Tarif horaire solo (Euros)",
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="fleet/photos/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="model_name",
            field=models.CharField(max_length=50, verbose_name="Modele"),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Disponible"),
                    ("MAINTENANCE", "En Maintenance"),
                    ("GROUNDED", "Cloue au sol (Panne)"),
                    ("RESERVED", "Reserve (Admin)"),
                ],
                default="AVAILABLE",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="block_off",
            field=models.TimeField(blank=True, null=True, verbose_name="Bloc Depart"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="block_on",
            field=models.TimeField(blank=True, null=True, verbose_name="Bloc Arrivee"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=8,
                verbose_name="Cout (Euros)",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="duration",
            field=models.DecimalField(
                decimal_places=2, editable=False, max_digits=5, verbose_name="Duree (h)"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="fuel_added",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                verbose_name="Essence Ajoutee (L)",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="hour_meter_end",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Compteur Arrivee"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="hour_meter_start",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Compteur Depart"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="landings_count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Nb Atterrissages"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="oil_added",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=4,
                verbose_name="Huile Ajoutee (L)",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="takeoff_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Decollage"),
        ),
        migrations.AlterField(
            model_name="maintenancedeadline",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description/Notes"),
        ),
        migrations.AlterField(
            model_name="maintenancedeadline",
            name="due_at_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Butee Calendaire"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancedeadline",
            name="due_at_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Butee Horaire",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancedeadline",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancedeadline",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titre"),
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Maintenance programmee"),
                            ("UNSCHEDULED", "Maintenance non programmee"),
                            ("REPAIR", "Reparation"),
                            ("MODIFICATION", "Modification"),
                            ("INSPECTION", "Inspection"),
                        ],
                        max_length=20,
                        verbose_name="Type travaux",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date travaux")),
                (
                    "hours_at_work",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Heures cellule"
                    ),
                ),
                (
                    "workshop",
                    models.CharField(max_length=100, verbose_name="Atelier/Mecanicien"),
                ),
                ("description", models.TextField(verbose_name="Description travaux")),
                (
                    "parts_replaced",
                    models.TextField(blank=True, verbose_name="Pieces remplacees"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cout (Euros)",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="N. facture"
                    ),
                ),
                (
                    "invoice_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="fleet/invoices/",
                        verbose_name="Scan facture",
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Approuve par (APRS)"
                    ),
                ),
                (
                    "approval_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference approbation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="fleet.aircraft",
                    ),
                ),
                (
                    "related_deadline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="fleet.maintenancedeadline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention maintenance",
                "verbose_name_plural": "Journal de maintenance",
                "ordering": ["-date"],
            },
        ),
    ]
