# Generated by Django 5.2.7 on 2025-12-23 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fleet", "0003_flight_block_off_flight_block_on_flight_complaints_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Certificat Médical"),
                            ("LICENSE", "Licence / Qualification"),
                            ("CDN", "Certificat de Navigabilité"),
                            ("MAINTENANCE", "Échéance Maintenance"),
                            ("BALANCE", "Solde Compte Bas"),
                            ("EXPERIENCE", "Expérience Récente"),
                            ("INSURANCE", "Assurance"),
                            ("COTISATION", "Cotisation Club"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Type d'alerte",
                    ),
                ),
                (
                    "days_info",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Nombre de jours avant expiration pour alerte INFO",
                        verbose_name="Jours avant (Info)",
                    ),
                ),
                (
                    "days_warning",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Nombre de jours avant expiration pour alerte WARNING",
                        verbose_name="Jours avant (Avertissement)",
                    ),
                ),
                (
                    "days_critical",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Nombre de jours avant expiration pour alerte CRITICAL",
                        verbose_name="Jours avant (Critique)",
                    ),
                ),
                (
                    "block_on_expiry",
                    models.BooleanField(
                        default=True,
                        help_text="Bloquer les réservations si expiré",
                        verbose_name="Bloquer à expiration",
                    ),
                ),
                (
                    "send_email",
                    models.BooleanField(default=True, verbose_name="Envoyer email"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Configuration Alerte",
                "verbose_name_plural": "Configurations Alertes",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Certificat Médical"),
                            ("LICENSE", "Licence / Qualification"),
                            ("CDN", "Certificat de Navigabilité"),
                            ("MAINTENANCE", "Échéance Maintenance"),
                            ("BALANCE", "Solde Compte Bas"),
                            ("EXPERIENCE", "Expérience Récente"),
                            ("INSURANCE", "Assurance"),
                            ("COTISATION", "Cotisation Club"),
                        ],
                        max_length=20,
                        verbose_name="Type d'alerte",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Avertissement"),
                            ("CRITICAL", "Critique"),
                            ("BLOCKING", "Bloquant"),
                        ],
                        default="WARNING",
                        max_length=20,
                        verbose_name="Sévérité",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Prise en compte"),
                            ("RESOLVED", "Résolue"),
                            ("EXPIRED", "Expirée"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message détaillé")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
                ),
                (
                    "expires_at",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date d'expiration concernée",
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Prise en compte le"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolue le"
                    ),
                ),
                (
                    "unique_key",
                    models.CharField(
                        help_text="Empêche la création de doublons (ex: medical_user_5_2025-06)",
                        max_length=200,
                        unique=True,
                        verbose_name="Clé unique",
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Email envoyé"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Email envoyé le"
                    ),
                ),
                (
                    "related_aircraft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="fleet.aircraft",
                        verbose_name="Avion concerné",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Membre concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
                "ordering": ["-severity", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="alerts_aler_user_id_286633_idx"
                    ),
                    models.Index(
                        fields=["alert_type", "status"],
                        name="alerts_aler_alert_t_82e8cd_idx",
                    ),
                    models.Index(
                        fields=["severity", "status"],
                        name="alerts_aler_severit_12d0e1_idx",
                    ),
                ],
            },
        ),
    ]
