# Generated by Django 6.0 on 2025-12-22 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de Licence"
                    ),
                ),
                (
                    "medical_validity",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Validité Médicale (Class 2/LAPL)",
                    ),
                ),
                (
                    "top_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="Validité Licence (SEP)"
                    ),
                ),
                (
                    "account_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Solde Compte (€)",
                    ),
                ),
                (
                    "is_instructor",
                    models.BooleanField(default=False, verbose_name="Est Instructeur"),
                ),
                (
                    "is_student",
                    models.BooleanField(default=False, verbose_name="Est Élève"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
            },
        ),
    ]
