# Generated by Django 5.2.7 on 2025-12-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_member_ffa_number_alter_member_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="license_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="members/licenses/",
                verbose_name="Scan Licence",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="medical_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="members/medical/",
                verbose_name="Scan Médical",
            ),
        ),
    ]
