# Generated by Django 5.2.7 on 2025-12-23 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_member_license_scan_member_medical_scan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aircraft_type",
                    models.CharField(max_length=50, verbose_name="Type avion"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                (
                    "requires_instructor_checkout",
                    models.BooleanField(
                        default=True, verbose_name="Necessite lacher instructeur"
                    ),
                ),
                (
                    "min_hours_required",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Heures min requises"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de qualification",
                "verbose_name_plural": "Types de qualifications",
            },
        ),
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["user__last_name", "user__first_name"],
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
            },
        ),
        migrations.RemoveField(
            model_name="member",
            name="top_validity",
        ),
        migrations.AddField(
            model_name="member",
            name="birth_place",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AddField(
            model_name="member",
            name="club_subscription_validity",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validite cotisation club"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_contact",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Contact urgence"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Tel. urgence"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="english_level",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Niveau Anglais (1-6)"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="english_validity",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validite Anglais"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="ffa_subscription_validity",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validite licence FFA"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="fi_validity",
            field=models.DateField(blank=True, null=True, verbose_name="Validite FI"),
        ),
        migrations.AddField(
            model_name="member",
            name="has_aerobatics",
            field=models.BooleanField(
                default=False, verbose_name="Qualification Voltige"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_english_level",
            field=models.BooleanField(
                default=False, verbose_name="Niveau Anglais OACI"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_fe",
            field=models.BooleanField(
                default=False, verbose_name="FE(A) - Examinateur"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_fi",
            field=models.BooleanField(
                default=False, verbose_name="FI(A) - Instructeur Vol"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_ir",
            field=models.BooleanField(
                default=False, verbose_name="IR - Vol aux instruments"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_mep",
            field=models.BooleanField(
                default=False, verbose_name="MEP(Land) - Multimoteur"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_mountain",
            field=models.BooleanField(
                default=False, verbose_name="Qualification Montagne"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_night",
            field=models.BooleanField(default=False, verbose_name="Qualification Nuit"),
        ),
        migrations.AddField(
            model_name="member",
            name="has_radio_certificate",
            field=models.BooleanField(
                default=False, verbose_name="Certificat Radiotelephonie"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_sep",
            field=models.BooleanField(
                default=False, verbose_name="SEP(Land) - Monomoteur"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_towing",
            field=models.BooleanField(
                default=False, verbose_name="Remorquage planeurs"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="insurance_validity",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validite assurance RC"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="ir_validity",
            field=models.DateField(blank=True, null=True, verbose_name="Validite IR"),
        ),
        migrations.AddField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Membre actif"),
        ),
        migrations.AddField(
            model_name="member",
            name="join_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date adhesion"),
        ),
        migrations.AddField(
            model_name="member",
            name="license_authority",
            field=models.CharField(
                default="DGAC France", max_length=50, verbose_name="Autorite delivrance"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="license_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date obtention brevet"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="license_issue_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date obtention licence"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("NONE", "Aucune licence"),
                    ("LAPL", "LAPL(A) - Light Aircraft Pilot Licence"),
                    ("PPL", "PPL(A) - Private Pilot Licence"),
                    ("CPL", "CPL(A) - Commercial Pilot Licence"),
                    ("ATPL", "ATPL(A) - Airline Transport Pilot Licence"),
                    ("ULM", "Brevet ULM"),
                    ("BB", "Brevet de Base (ancien)"),
                ],
                default="NONE",
                max_length=10,
                verbose_name="Type de licence",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="medical_class",
            field=models.CharField(
                choices=[
                    ("NONE", "Aucun"),
                    ("LAPL", "Medical LAPL"),
                    ("CLASS2", "Classe 2"),
                    ("CLASS1", "Classe 1"),
                ],
                default="NONE",
                max_length=10,
                verbose_name="Classe medicale",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="medical_restrictions",
            field=models.TextField(blank=True, verbose_name="Restrictions medicales"),
        ),
        migrations.AddField(
            model_name="member",
            name="member_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="N. Adherent Club",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="mep_validity",
            field=models.DateField(blank=True, null=True, verbose_name="Validite MEP"),
        ),
        migrations.AddField(
            model_name="member",
            name="mountain_skis",
            field=models.BooleanField(default=False, verbose_name="Montagne Skis"),
        ),
        migrations.AddField(
            model_name="member",
            name="mountain_wheels",
            field=models.BooleanField(default=False, verbose_name="Montagne Roues"),
        ),
        migrations.AddField(
            model_name="member",
            name="nationality",
            field=models.CharField(
                default="Francaise", max_length=50, verbose_name="Nationalite"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="night_validity",
            field=models.DateField(blank=True, null=True, verbose_name="Validite Nuit"),
        ),
        migrations.AddField(
            model_name="member",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes internes"),
        ),
        migrations.AddField(
            model_name="member",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="members/photos/",
                verbose_name="Photo identite",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Code postal"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="radio_certificate_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date certificat radio"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="radio_certificate_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N. Certificat Radio"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="sep_validity",
            field=models.DateField(blank=True, null=True, verbose_name="Validite SEP"),
        ),
        migrations.AddField(
            model_name="member",
            name="solo_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date premier solo"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="total_flight_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Heures de vol totales declarees",
                max_digits=7,
                verbose_name="Heures totales",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="account_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Solde Compte (Euros)",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="ffa_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N. Licence FFA"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="Est Eleve"),
        ),
        migrations.AlterField(
            model_name="member",
            name="license_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numero de Licence"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="medical_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="members/medical/",
                verbose_name="Scan Medical",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="medical_validity",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validite Medicale"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telephone"),
        ),
        migrations.CreateModel(
            name="MemberTypeQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_date", models.DateField(verbose_name="Date du lacher")),
                ("notes", models.TextField(blank=True, verbose_name="Remarques")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_qualifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Instructeur",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_qualifications",
                        to="members.member",
                    ),
                ),
                (
                    "qualification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.qualificationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualification type",
                "verbose_name_plural": "Qualifications types",
                "unique_together": {("member", "qualification_type")},
            },
        ),
    ]
