# Generated by Django 5.2.7 on 2025-12-23 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_qualificationtype_alter_member_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("LICENSE", "Licence pilote"),
                            ("MEDICAL", "Certificat medical"),
                            ("INSURANCE", "Assurance RC"),
                            ("FFA", "Licence FFA"),
                            ("RADIO", "Certificat radiotelephonie"),
                            ("ENGLISH", "Certificat Anglais OACI"),
                            ("ID", "Piece d'identite"),
                            ("CLUB", "Cotisation club"),
                            ("CHECKOUT", "Lacher machine"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                (
                    "file",
                    models.FileField(
                        upload_to="members/documents/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'emission"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'upload"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente de validation"),
                            ("VALID", "Valide"),
                            ("EXPIRED", "Expire"),
                            ("REJECTED", "Refuse"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "validation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date validation"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif de refus"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Le document le plus recent de ce type pour ce membre",
                        verbose_name="Document actuel",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="members.member",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Valide par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document membre",
                "verbose_name_plural": "Documents membres",
                "ordering": ["-upload_date"],
            },
        ),
    ]
